### ISSUE TITLE
OH MY GOD!!

### ISSUE THREAD

**Issue by lord666** [LogicBreakers/Public#1]
I 'm sorry but this release flood completely hearthstone and make it unplayable.
and the old version is gone (she was recognized as virus since some days)
For  the best now ..muligan sliverfish works and hearthstone don't crash when i click on playing button for stop it  ... !! "courage" !! :D

**Comment by LogicBreakers** [comment]
Hello, this is a test release that its still not ready we're working to get it fully working :)
